/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SzsbTmZxBwb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { ResponsiveLine } from "@nivo/line"
import { Button } from "@/components/ui/button"
import { ResponsiveBar } from "@nivo/bar"
import { BellIcon, CurrencyIcon, DotIcon, GroupIcon, HelpCircleIcon } from "lucide-react"

export function StatsChart() {
  return (
    <div className="bg-white p-8">
      <div className="flex justify-between">
        <Input className="flex-1" placeholder="Search anything here..." />
        <div className="flex items-center space-x-4">
          <BellIcon className="text-gray-600" />
          <Avatar>
            <AvatarImage alt="John Doe" src="/placeholder.svg?height=32&width=32" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <span className="font-semibold">John Doe</span>
          <ChevronDownIcon className="text-gray-600" />
        </div>
      </div>
      <h1 className="mt-8 mb-4 text-4xl font-bold">Statistics</h1>
      <div className="grid grid-cols-4 gap-4">
        <Card className="bg-[#F0FDF4]">
          <CardContent>
            <GroupIcon className="text-[#4ADE80]" />
            <p className="text-2xl font-bold">126</p>
            <p className="text-sm text-gray-500">Total Users</p>
          </CardContent>
        </Card>
        <Card className="bg-[#FEF3C7]">
          <CardContent>
            <CurrencyIcon className="text-[#FDE047]" />
            <p className="text-2xl font-bold">₦265,795</p>
            <p className="text-sm text-gray-500">Revenue</p>
          </CardContent>
        </Card>
        <Card className="bg-[#FEF3C7]">
          <CardContent>
            <CurrencyIcon className="text-[#FDE047]" />
            <p className="text-2xl font-bold">79</p>
            <p className="text-sm text-gray-500">Total Deposits</p>
          </CardContent>
        </Card>
        <Card className="bg-[#F0FDF4]">
          <CardContent>
            <GroupIcon className="text-[#4ADE80]" />
            <p className="text-2xl font-bold">17</p>
            <p className="text-sm text-gray-500">Total Groups</p>
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-3 gap-4 mt-4">
        <Card className="col-span-1">
          <CardContent>
            <div className="flex justify-between">
              <h2 className="text-xl font-bold">All Requests</h2>
              <DotIcon className="text-gray-600" />
            </div>
            <div className="mt-4">
              <Badge variant="secondary">1132 Requests</Badge>
            </div>
          </CardContent>
        </Card>
        <Card className="col-span-2">
          <CardContent>
            <div className="flex justify-between">
              <h2 className="text-xl font-bold">Revenue Overview</h2>
              <Select>
                <SelectTrigger id="month">
                  <SelectValue placeholder="This Month" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="january">January</SelectItem>
                  <SelectItem value="february">February</SelectItem>
                  <SelectItem value="march">March</SelectItem>
                  <SelectItem value="april">April</SelectItem>
                  <SelectItem value="may">May</SelectItem>
                  <SelectItem value="june">June</SelectItem>
                  <SelectItem value="july">July</SelectItem>
                  <SelectItem value="august">August</SelectItem>
                  <SelectItem value="september">September</SelectItem>
                  <SelectItem value="october">October</SelectItem>
                  <SelectItem value="november">November</SelectItem>
                  <SelectItem value="december">December</SelectItem>
                </SelectContent>
              </Select>
              <Select>
                <SelectTrigger id="year">
                  <SelectValue placeholder="2022" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="2022">2022</SelectItem>
                  <SelectItem value="2023">2023</SelectItem>
                  <SelectItem value="2024">2024</SelectItem>
                </SelectContent>
              </Select>
              <DotIcon className="text-gray-600" />
            </div>
            <CurvedlineChart className="w-full h-[300px]" />
          </CardContent>
        </Card>
      </div>
      <div className="grid grid-cols-3 gap-4 mt-4">
        <Card className="col-span-2">
          <CardContent>
            <div className="flex justify-between">
              <h2 className="text-xl font-bold">Transactions</h2>
              <div className="flex items-center space-x-2">
                <Button size="sm" variant="ghost">
                  Today
                </Button>
                <span className="text-sm text-gray-500">09/04/2023</span>
                <DotIcon className="text-gray-600" />
              </div>
            </div>
            <BarChart className="w-full h-[300px]" />
          </CardContent>
        </Card>
        <Card className="col-span-1">
          <CardContent>
            <div className="flex justify-between">
              <h2 className="text-xl font-bold">Cards</h2>
              <DotIcon className="text-gray-600" />
            </div>
            <div className="flex justify-between mt-4">
              <div>
                <p className="text-2xl font-bold">05</p>
                <p className="text-sm text-gray-500">Physical</p>
              </div>
              <div>
                <p className="text-2xl font-bold">05</p>
                <p className="text-sm text-gray-500">Virtual</p>
              </div>
            </div>
            <div className="mt-4">
              <h3 className="text-lg font-semibold">Drivers</h3>
              <div className="mt-2">
                <Avatar>
                  <AvatarImage alt="Ayo Okoye" src="/placeholder.svg?height=32&width=32" />
                  <AvatarFallback>AO</AvatarFallback>
                </Avatar>
                <span className="ml-2 font-medium">Ayo Okoye</span>
                <Badge className="ml-auto" variant="secondary">
                  +40
                </Badge>
              </div>
              <div className="mt-2">
                <Avatar>
                  <AvatarImage alt="Owolabi Ajif" src="/placeholder.svg?height=32&width=32" />
                  <AvatarFallback>OA</AvatarFallback>
                </Avatar>
                <span className="ml-2 font-medium">Owolabi Ajif</span>
                <Badge className="ml-auto" variant="secondary">
                  +60
                </Badge>
              </div>
            </div>
            <Button className="mt-4 w-full justify-center" variant="ghost">
              <HelpCircleIcon className="text-gray-600" />
              <span className="ml-2">Support</span>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

export function BarChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.6}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "8px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}

export function CurvedlineChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
